apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: ld2023
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: be-deploy
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
